### ISSUE TITLE
Error in copying code

### ISSUE THREAD

**Issue by JunsFu** [FeipengMa6/PriSA#3]
![image](https://github.com/FeipengMa6/PriSA/assets/100461491/a2e75e18-c0f4-4dd3-b77f-cab31d8a8521)

Hello, thank you for your excellent work, I was very interested in this article!
I encountered the following error while reproducing the code:
Because the folder name saved during runtime is too long, "nesting" behavior occurs, resulting in an error.
See the picture above for specific effects.
Looking forward to your answer, thank you!

**Comment by FeipengMa6** [comment]
Apologies for the confusion! The error occurred because you placed the log path inside the project folder, causing the log dir to be repeatedly copied. 
I have updated the code, please refer to the training section of `README.md`. Now you can use `python main.py` to run the code, and the results will be saved at `./logs`.
I hope this will help you!
